# Generated by Django 2.0 on 2018-08-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='练习a网',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名字', models.CharField(max_length=30)),
                ('年龄', models.IntegerField()),
            ],
        ),
    ]
