# Generated by Django 2.0 on 2018-08-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('模型数据库', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='练习a网',
            new_name='wanA',
        ),
    ]
