# Generated by Django 2.0 on 2018-08-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('模型数据库', '0002_auto_20180809_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wanA',
            new_name='练习a网',
        ),
    ]
